from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app.config import Settings, get_settings
from app.main import create_app


@pytest.fixture
def client() -> TestClient:
    """App wired to blank settings so tests never read a developer's backend/.env."""
    app = create_app()
    app.dependency_overrides[get_settings] = lambda: Settings(_env_file=None)
    return TestClient(app)


SYNTHETIC_ROOT = Path(__file__).resolve().parents[2] / "data" / "synthetic"


@pytest.fixture(scope="session")
def acme_data():
    """The committed synthetic Acme engagement (deterministic, generated by scripts.synthetic)."""
    from app.services.engagement_data import EngagementDataRepository

    return EngagementDataRepository(SYNTHETIC_ROOT).load("acme-2025")
