import os
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

# app.main builds the app (and configures tracing) at import time, so the telemetry switches must
# be pinned before it is imported - never export or look up Application Insights from tests.
os.environ["OTEL_USE_FOUNDRY_APP_INSIGHTS"] = "false"
os.environ["APPLICATIONINSIGHTS_CONNECTION_STRING"] = ""
os.environ["OTEL_CONSOLE_EXPORT"] = "false"

from app.config import Settings, get_settings  # noqa: E402
from app.main import create_app  # noqa: E402


@pytest.fixture(autouse=True)
def _fresh_settings():
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


@pytest.fixture
def client() -> TestClient:
    """App wired to blank settings so tests never read a developer's backend/.env."""
    app = create_app()
    app.dependency_overrides[get_settings] = lambda: Settings(_env_file=None)
    return TestClient(app)


SYNTHETIC_ROOT = Path(__file__).resolve().parents[2] / "data" / "synthetic"


@pytest.fixture(scope="session")
def acme_data():
    """The committed synthetic Acme engagement (deterministic, generated by scripts.synthetic)."""
    from app.services.engagement_data import EngagementDataRepository

    return EngagementDataRepository(SYNTHETIC_ROOT).load("acme-2025")
